### ISSUE TITLE
"Socket closed" exceptions in tests

### ISSUE THREAD

**Issue by xerus2000** [CAU-Kiel-Tech-Inf/backend#264]

**Comment by xerus2000** [comment]
https://travis-ci.com/github/CAU-Kiel-Tech-Inf/backend/builds/186628332
```
sc.server.LobbyTest > shouldConnectAndDisconnect FAILED

    java.lang.AssertionError at LobbyTest.kt:23

10:23:38.072 [XStreamClient ReceiveThread id:155 client:Client] WARN sc.networking.clients.XStreamClient - Client sc.server.network.Client@73eb51fe disconnected (Cause: LOST_CONNECTION, Exception: {})

com.thoughtworks.xstream.io.StreamException: 

com.thoughtworks.xstream.io.StreamException: 

	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:69)

	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:69)

	at com.thoughtworks.xstream.XStream.createObjectInputStream(XStream.java:2161)

	at com.thoughtworks.xstream.XStream.createObjectInputStream(XStream.java:2161)

	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:93)

	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:93)

	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)

	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:77)

	at java.lang.Thread.run(Thread.java:748)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.net.SocketException: Socket closed

Caused by: java.net.SocketException: Socket closed

	at java.net.SocketInputStream.socketRead0(Native Method)

	at java.net.SocketInputStream.socketRead0(Native Method)

	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

	at java.net.SocketInputStream.read(SocketInputStream.java:171)

	at java.net.SocketInputStream.read(SocketInputStream.java:171)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at java.net.SocketInputStream.read(SocketInputStream.java:224)

	at java.net.SocketInputStream.read(SocketInputStream.java:224)

	at java.io.FilterInputStream.read(FilterInputStream.java:83)

	at java.io.FilterInputStream.read(FilterInputStream.java:83)

	at java.io.PushbackInputStream.read(PushbackInputStream.java:139)

	at java.io.PushbackInputStream.read(PushbackInputStream.java:139)

	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.getHeader(XmlHeaderAwareReader.java:79)

	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.getHeader(XmlHeaderAwareReader.java:79)

	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.<init>(XmlHeaderAwareReader.java:61)

	at com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.<init>(XmlHeaderAwareReader.java:61)

	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)

	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)

	... 4 common frames omitted

	... 4 more

10:23:38.074 [XStreamClient ReceiveThread id:155 client:Client] WARN sc.networking.clients.XStreamClient - Attempted to close an already closed stream

10:23:38.074 [XStreamClient ReceiveThread id:155 client:Client] DEBUG sc.networking.clients.XStreamClient - Terminated XStreamClient ReceiveThread id:155 client:Client

33 tests completed, 1 failed, 5 skipped

> Task :server:test FAILED
```

**Comment by xerus2000** [comment]
Happens when the CloseConnection is not processed before a new packet is sent. Not really problematic, just annoying.
