### ISSUE TITLE
SimpleClient (oder anderer Client) startet nicht 

### ISSUE THREAD

**Issue by 0xhtml** [CAU-Kiel-Tech-Inf/backend#306]
Kein Client lässt sich bei mir auf dem Server starten. Es kommt immer zu java.io.EOFExceptions beim Server und zu com.thoughtworks.xstream.converters.ConversionExceptions bei beiden Clients, sobald das Spiel beginnen soll.
<details><summary>Serverlog</summary>
<p>

```
16:54:42.074 [XStreamClient ReceiveThread id:14 client:Client] WARN sc.networking.clients.XStreamClient - Client sc.server.network.Client@65db1b39 disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2075)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:473)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:440)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:99)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
16:54:42.075 [XStreamClient ReceiveThread id:14 client:Client] INFO sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:14 client:Client
16:54:42.075 [XStreamClient ReceiveThread id:14 client:Client] WARN sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
16:54:42.076 [XStreamClient ReceiveThread id:14 client:Client] DEBUG sc.networking.clients.XStreamClient - Failed to close OUT
com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:77)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.endNode(PrettyPrintWriter.java:322)
	at com.thoughtworks.xstream.io.WriterWrapper.endNode(WriterWrapper.java:37)
	at com.thoughtworks.xstream.io.StatefulWriter.endNode(StatefulWriter.java:134)
	at com.thoughtworks.xstream.XStream$3.close(XStream.java:2013)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.close(CustomObjectOutputStream.java:149)
	at sc.networking.clients.XStreamClient.close(XStreamClient.java:250)
	at sc.networking.clients.XStreamClient.handleDisconnect(XStreamClient.java:201)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:127)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:75)
	... 10 common frames omitted
```

[Ganzer Log](https://github.com/CAU-Kiel-Tech-Inf/backend/files/5433054/server.log)
</p>
</details>

<details><summary>Clientlog</summary>
<p>

```
16:54:42 WARN  sc.networking.clients.XStreamClient - Client sc.networking.clients.LobbyClient@77af058e disconnected (Cause: PROTOCOL_ERROR, Exception: {})
com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : state
class               : sc.protocol.responses.MementoPacket
required-type       : sc.protocol.responses.MementoPacket
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 8
class[1]            : sc.protocol.responses.RoomPacket
required-type[1]    : sc.protocol.responses.RoomPacket
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:499)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:425)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1404)
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2078)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:473)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:440)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:99)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: state
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:420)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 17 common frames omitted
16:54:42 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:11 client:LobbyClient
16:54:42 WARN  sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
```

[Ganzer Log](https://github.com/CAU-Kiel-Tech-Inf/backend/files/5433056/clientA.log)
[Zweiter Client Log](https://github.com/CAU-Kiel-Tech-Inf/backend/files/5433058/clientB.log)
</p>
</details>

<details><summary>Systeminformationen</summary>
<p>

```
Linux 5.8.14-arch1-1 x86_64 GNU/Linux

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)
```

</p>
</details>

**Comment by SKoschnicke** [comment]
Danke für den ausführlichen Bericht! Welche Version von Server und SimpleClient wurde verwendet? Die neueste? Also GUI 21.0.7 beziehungsweise Server 21.0.2?

**Comment by 0xhtml** [comment]
Ja, Serverversion `21.0.2`. Der Client war die `defaultplayer.jar` aus dem Server-Zip.

**Comment by xerus2000** [comment]
@0xhtml wir sind dran, der Fix sollte in kürze bereit sein :)

**Comment by 0xhtml** [comment]
Fehler tritt mit der neuen Version 21.0.3 nicht mehr auf.
