### ISSUE TITLE
v21.1.0 regression: Pause not working

### ISSUE THREAD

**Issue by Coronon** [CAU-Kiel-Tech-Inf/backend#332]
Since version 21.1.0 the server ignores the admin clients request to pause the game.
It just starts the game when two clients join with their reservations. 100% reproducibility.

AdminClient<->Server communication:
[Wireshark_PauseIgnored.pdf](https://github.com/CAU-Kiel-Tech-Inf/backend/files/5542506/Wireshark_PauseIgnored.pdf)

Server log (note that the pasue->false is sent 1.5 seconds after the clients connect as this avoids another bug that happened in the previous version)
```txt
15:16:08,050 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/mnt/r/Informatik/SWC-2021/PyBlokusTools/pyblokustools/testserver/swcServer/logback.xml]
15:16:08,180 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:16:08,181 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:16:08,195 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
15:16:08,234 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@77f03bb1 - Will use gz compression
15:16:08,310 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:16:08,310 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:16:08,310 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:16:08,310 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: log/game_server.log
15:16:08,310 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [log/game_server.log]
15:16:08,311 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:16:08,312 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:16:08,313 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
15:16:08,314 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:16:08,314 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:16:08,314 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:16:08,315 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sc] to INFO
15:16:08,315 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:16:08,315 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
15:16:08,315 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:16:08,315 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:16:08,316 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@326de728 - Registering current configuration as safe fallback point

15:16:08 INFO  sc.server.Application - Server is starting up...
15:16:08 INFO  sc.server.Configuration - Loading configuration from /mnt/r/Informatik/SWC-2021/PyBlokusTools/pyblokustools/testserver/swcServer/server.properties
15:16:08 INFO  sc.server.network.NewClientListener - Listening on port 13055 for incoming connections.
15:16:08 INFO  sc.server.network.ClientManager - ClientManager running
15:16:12 INFO  sc.server.network.NewClientListener - A Client connected...
15:16:12 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@2d37c03d to ReadyQueue.
15:16:12 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
15:16:12 INFO  sc.server.network.ClientManager - Delegation done
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
15:16:12 INFO  sc.server.network.Client - Client authenticated as administrator
15:16:14 INFO  sc.server.gaming.GameRoomManager - Created new game of type swc_2021_blokus
15:16:14 WARN  sc.server.gaming.GameRoom - Dropped unnecessary PAUSE toggle from false to false.
15:16:15 INFO  sc.server.network.NewClientListener - A Client connected...
15:16:15 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@1692a3cf to ReadyQueue.
15:16:15 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
15:16:15 INFO  sc.server.network.ClientManager - Delegation done
15:16:15 INFO  sc.server.network.NewClientListener - A Client connected...
15:16:15 INFO  sc.server.network.NewClientListener - Added Client sc.server.network.Client@5546babe to ReadyQueue.
15:16:15 INFO  sc.server.network.ClientManager - Delegating new client to ClientManager...
15:16:15 INFO  sc.server.network.ClientManager - Delegation done
15:16:15 INFO  sc.server.gaming.ReservationManager - Reservation 302c2690-5014-49bc-b63a-f794b1701c47 was redeemed.
15:16:15 INFO  sc.server.gaming.GameRoom - Game isn't ready yet.
15:16:15 INFO  sc.server.gaming.ReservationManager - Reservation 274dcef8-9c6c-4cae-acbb-620529292957 was redeemed.
15:16:15 INFO  sc.server.gaming.GameRoom - Updating Status to ACTIVE (was: CREATED)
15:16:15 INFO  sc.server.gaming.GameRoom - Started the game.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 10
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 5
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 6
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 25
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 17
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 9
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 46
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 53
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:15 INFO  sc.framework.plugins.ActionTimeout - Time needed: 38
15:16:15 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 163
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 WARN  sc.server.gaming.GameRoom - Dropped unnecessary PAUSE toggle from false to false.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 58
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 28
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 10
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 6
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 24
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 5
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:16 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:16 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 5
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 4
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 10
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 20
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 5
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 3
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 12
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 5
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 4
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 11
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:17 INFO  sc.framework.plugins.ActionTimeout - Time needed: 10
15:16:17 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 0
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.plugin2021.GameState - Removing GREEN from the game
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.plugin2021.GameState - Removing YELLOW from the game
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 4
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 2
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 0
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 1
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.plugin2021.GameState - Removing RED from the game
15:16:18 INFO  sc.framework.plugins.ActionTimeout - Time needed: 0
15:16:18 INFO  sc.framework.plugins.ActionTimeout - HardTimout wasn't reached.
15:16:18 INFO  sc.plugin2021.GameState - Removing BLUE from the game
15:16:18 INFO  sc.server.gaming.GameRoom - Updating Status to OVER (was: ACTIVE)
15:16:18 INFO  sc.server.gaming.GameRoom - The game dbfcffec-6604-4879-84b8-595be795aaed is over. (regular=true)
15:16:18 INFO  s.f.plugins.RoundBasedGameInstance - Destroying Game
15:16:18 WARN  sc.framework.plugins.ActionTimeout - Timeout was already stopped.
15:16:18 WARN  sc.networking.clients.XStreamClient - Client sc.server.network.Client@1692a3cf disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2075)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:494)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:99)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.lang.Thread.run(Thread.java:748)
15:16:18 WARN  sc.networking.clients.XStreamClient - Client sc.server.network.Client@5546babe disconnected (Cause: LOST_CONNECTION, Exception: {})
java.io.EOFException: null
	at com.thoughtworks.xstream.XStream$4.readFromStream(XStream.java:2075)
	at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:123)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:494)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:99)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.lang.Thread.run(Thread.java:748)
15:16:18 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:13 client:Client
15:16:18 INFO  sc.networking.clients.XStreamClient - Stopping XStreamClient ReceiveThread id:14 client:Client
15:16:18 WARN  sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
15:16:18 WARN  sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
15:16:18 INFO  sc.server.gaming.GameRoom - Removing Player Two(Client2) from sc.server.gaming.GameRoom@391fdcb7
15:16:18 WARN  sc.server.gaming.GameRoom - Game was already over but received another GameOver-Event.
15:16:18 INFO  sc.server.gaming.GameRoom - Removing Player One(Client1) from sc.server.gaming.GameRoom@391fdcb7
15:16:18 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@5546babe from client manager
15:16:18 INFO  sc.server.Lobby - sc.server.network.Client@5546babe disconnected.
15:16:18 WARN  sc.server.gaming.GameRoom - Game was already over but received another GameOver-Event.
15:16:18 INFO  sc.server.network.ClientManager - Removing client sc.server.network.Client@1692a3cf from client manager
15:16:18 INFO  sc.server.Lobby - sc.server.network.Client@1692a3cf disconnected.
```

After one game has already been played, the server adds this exception to the end of the previous log for all games:
```txt
15:21:32 ERROR sc.server.Lobby - Got exception on pause: {}
sc.api.plugins.exceptions.RescuableClientException: Couldn't find a room with id 60ddef84-f639-4fd7-8a1e-4878104b4a9a
	at sc.server.gaming.GameRoomManager.findRoom(GameRoomManager.java:213)
	at sc.server.Lobby.onRequest(Lobby.kt:95)
	at sc.server.network.Client.notifyOnPacket(Client.java:76)
	at sc.server.network.Client.onObject(Client.java:206)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:110)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xerus2000** [comment]
This looks suspicious:

    15:16:14 WARN  sc.server.gaming.GameRoom - Dropped unnecessary PAUSE toggle from false to false.

**Comment by Coronon** [comment]
> 
> 
> This looks suspicious:
> 
> ```
> 15:16:14 WARN  sc.server.gaming.GameRoom - Dropped unnecessary PAUSE toggle from false to false.
> ```

It does this when creating a normal game (without pause=true) too though. -> Maybe it just doesnt recognize the flag in the xml anymore?

```txt
15:44:07 INFO  sc.server.network.Client - Client authenticated as administrator
15:44:09 INFO  sc.server.gaming.GameRoomManager - Created new game of type swc_2021_blokus
15:44:09 WARN  sc.server.gaming.GameRoom - Dropped unnecessary PAUSE toggle from false to false.
```

**Comment by xerus2000** [comment]
The parameter `shouldBePaused="true` is obsolete with the new version, it is now part of the PrepareGameRequest itself. XML Documentation is probably not updated yet.

**Comment by Coronon** [comment]
> 
> 
> Btw, the parameter `shouldBePaused="true` is obsolete with the new version, it is now part of the PrepareGameRequest itself. XML Documentation is probably not updated yet.

Nope, the current docs state:
```xml
<prepare gameType="swc_2021_blokus">
  <slot displayName="p1" canTimeout="false" shouldBePaused="true" />
  <slot displayName="p2" canTimeout="false" shouldBePaused="true" />
</prepare>
```

**Comment by xerus2000** [comment]
Docs are updated now :)
In the wireshark log the pause request is

    <pause roomId="dbfcffec-6604-4879-84b8-595be795aaed" pause="false" />

maybe that is simply the problem? ^^

**Comment by Coronon** [comment]
> 
> 
> Docs are updated now :)
> In the wireshark log the pause request is
> 
> ```
> <pause roomId="dbfcffec-6604-4879-84b8-595be795aaed" pause="false" />
> ```
> 
> maybe that is simply the problem? ^^

That is not the pause request, that's when our testing system wants to _unpause_ the game as soon as it has resources available ;)
We try to create the game paused, as was stated in the old documentation.

Thx for the effort :+1:

**Comment by xerus2000** [comment]
> Since version 21.1.0 the server ignores the admin clients request to pause the game.

Ah, again not quite clear - it sounded like you intended to send a pause request after game creation, rather than at game creation.

**Comment by Coronon** [comment]
> 
> 
> > Since version 21.1.0 the server ignores the admin clients request to pause the game.
> 
> Ah, again not quite clear - it sounded like you intended to send a pause request after game creation, rather than at game creation.

Looking at the PDF, one can clearly see that we tried to create the game paused (just like the docs described the procedure at that time):

```xml
<preparegameType="swc_2021_blokus">
    <slot displayName="Client1" canTimeout="true" shouldBePaused="true" />
    <slot displayName="Client2" canTimeout="true" shouldBePaused="true" />
</prepare>
```
