### ISSUE TITLE
Active player is null when unpausing a prepared paused game

### ISSUE THREAD

**Issue by Coronon** [CAU-Kiel-Tech-Inf/backend#378]
When creating a paused game with the admin client, observing it, starting players with the reservation codes and then unpausing the game, the server drops the connection to the admin client, does not log the game but stil plays it with the clients.

Server log:
```
20:52:04,865 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/tmp/blokusmass_w6i9erex/logback.xml]
20:52:04,929 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:52:04,930 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
20:52:04,938 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
20:52:04,961 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@77f03bb1 - Will use gz compression
20:52:05,003 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
20:52:05,003 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
20:52:05,003 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
20:52:05,003 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: log/game_server.log
20:52:05,003 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [log/game_server.log]
20:52:05,004 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:52:05,006 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
20:52:05,007 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
20:52:05,007 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
20:52:05,007 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
20:52:05,007 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sc] to INFO
20:52:05,007 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
20:52:05,008 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
20:52:05,008 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
20:52:05,008 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:52:05,009 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@326de728 - Registering current configuration as safe fallback point

20:52:05.01 INFO                 sc.server.Application - Server is starting up...
20:52:05.06 INFO               sc.server.Configuration - Loading configuration from /tmp/blokusmass_w6i9erex/server.properties
20:52:05.09 INFO   sc.server.network.NewClientListener - Listening on port 13060 for incoming connections.
20:52:05.09 INFO       sc.server.network.ClientManager - ClientManager running
20:52:09.69 INFO   sc.server.network.NewClientListener - A Client connected...
20:52:09.94 INFO       sc.server.network.ClientManager - Delegating new client to ClientManager...
20:52:09.94 INFO   sc.server.network.NewClientListener - Added Client Client@20719f8b to ReadyQueue.
20:52:09.94 INFO       sc.server.network.ClientManager - Delegation done
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
20:52:09.96 INFO              sc.server.network.Client - Client authenticated as administrator
20:52:11.72 INFO      sc.server.gaming.GameRoomManager - Created new game of type swc_2021_blokus
20:52:11.80 INFO             sc.server.gaming.GameRoom - Toggling PAUSE from false to true
20:52:12.32 INFO             sc.server.gaming.GameRoom - Toggling PAUSE from true to false
20:52:12.32 INFO     sc.framework.plugins.AbstractGame - Sending MoveRequest to player null
20:52:12.33 ERROR  sc.networking.clients.XStreamClient - Unknown Communication Error
java.lang.IllegalStateException: Trying to notify active player but it is null
	at sc.framework.plugins.AbstractGame.notifyActivePlayer(AbstractGame.kt:157)
	at sc.framework.plugins.AbstractGame.afterPause(AbstractGame.kt:35)
	at sc.server.gaming.GameRoom.pause(GameRoom.java:509)
	at sc.server.Lobby.onRequest(Lobby.kt:96)
	at sc.server.network.Client.notifyOnPacket(Client.java:74)
	at sc.server.network.Client.onObject(Client.java:202)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:107)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:72)
	at java.lang.Thread.run(Thread.java:748)
20:52:12.33 WARN   sc.networking.clients.XStreamClient - Client@20719f8b disconnected (Cause: UNKNOWN, Exception: {})
java.lang.IllegalStateException: Trying to notify active player but it is null
	at sc.framework.plugins.AbstractGame.notifyActivePlayer(AbstractGame.kt:157)
	at sc.framework.plugins.AbstractGame.afterPause(AbstractGame.kt:35)
	at sc.server.gaming.GameRoom.pause(GameRoom.java:509)
	at sc.server.Lobby.onRequest(Lobby.kt:96)
	at sc.server.network.Client.notifyOnPacket(Client.java:74)
	at sc.server.network.Client.onObject(Client.java:202)
	at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:107)
	at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:72)
	at java.lang.Thread.run(Thread.java:748)
20:52:12.33 INFO   sc.networking.clients.XStreamClient - Stopping XStream-Receive id:12 of Client@20719f8b
20:52:12.33 WARN   sc.networking.clients.XStreamClient - ReceiveThread is stopping itself
20:52:12.33 INFO       sc.server.network.ClientManager - Removing client Client@20719f8b from client manager
20:52:12.33 INFO                       sc.server.Lobby - Client@20719f8b disconnected.
```

Messages between the Server and AdminClient:
[YetAnotherOne.pdf](https://github.com/CAU-Kiel-Tech-Inf/backend/files/5921163/YetAnotherOne.pdf)

After the last message by the server the connection is reset and closed.

**Comment by xerus2000** [comment]
The Game ist still played? That's weird, I think I know the origin of the error but the Game shouldn't continue normally after that...

**Comment by xerus2000** [comment]
Proper testing should probably come from #363

**Comment by Coronon** [comment]
> 
> 
> The Game ist still played? That's weird, I think I know the origin of the error but the Game shouldn't continue normally after that...

I though the same, but I can see the traffic through wireshark and our clients log output, its just the Admin-Client that gets booted out

**Comment by xerus2000** [comment]
not able to reproduce this so far - wrote a corresponding test in https://github.com/CAU-Kiel-Tech-Inf/backend/pull/363/commits/3f52c57790295a7c80cddebaca9e482a432dfb11 which succeeds

**Comment by Coronon** [comment]
I have a 100% reproducibility with our old tooling versions. It seems to be about timing, so manual tests will not discover the bug.

**Comment by xerus2000** [comment]
"our old tooling versions" means which version? I think I have changed some of that code recently.

When the game is started, `activePlayer` is always set (otherwise there is an exception), so what you are encountering is weird. Maybe `unpause` is triggered even before the game is started?

**Comment by xerus2000** [comment]
Yep, that should be it.
