### ISSUE TITLE
TestClient test times out due to erronous PlayerScoreRequest

### ISSUE THREAD

**Issue by xerus2000** [CAU-Kiel-Tech-Inf/backend#386]
```sh
java.lang.IllegalArgumentException: Score for "player1" could not be found!
    at sc.server.Lobby.onRequest(Lobby.kt:114)
    at sc.server.network.Client.notifyOnPacket(Client.java:64)
    at sc.server.network.Client.onObject(Client.java:195)
    at sc.networking.clients.XStreamClient.receiveThread(XStreamClient.java:107)
    at sc.networking.clients.XStreamClient$1.run(XStreamClient.java:72)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by xerus2000** [comment]
https://github.com/CAU-Kiel-Tech-Inf/backend/runs/1879033740

This doesn't happen always though :thinking:

**Comment by xerus2000** [comment]
Fixed in https://github.com/CAU-Kiel-Tech-Inf/backend/commit/4f33fc01f1cddbebe86bec0cf7b285a372c77df9
